services:
  strapi:
  # Build configuration for Strapi service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bblcc-strapi
    image: bblcc_strapi_dev
    restart: on-failure
    env_file: .env
    environment:
    # Environment variables for database configuration
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    # Port mapping for Strapi service  
    ports:
      - "1337:1337"
    # Networking configuration for Strapi service
    networks:
      - strapi
networks:
  strapi:
    # Definition of Strapi network
    name: Strapi
    driver: bridge